AWSTemplateFormatVersion: 2010-09-09
Description: AWSHOMEDB

Transform:
  - AWS::Serverless-2016-10-31

# 🔐 GLOBAL VARIABLES: Automatically injected into EVERY function below
Globals:
  Function:
    Environment:
      Variables:
        TABLE_NAME: !Ref AWSHomeDBTable
        # AUTH_SECRET: !Sub "${AWS::StackName}-auth-secret"
        # AUTH_SECRET: !Sub "StagingAuthSecretKey2026"
        AUTH_SECRET: !Sub "StagingAuthSecretKey2026"

Parameters:
  StageName:
    Type: String
    Default: Stage
    Description: "The deployment stage name passed from your branch workflow"

Resources:

  # =========================
  # HTTP API
  # =========================
  MyServerlessApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      Description: "AWSHomeDB HTTP API"

      CorsConfiguration:
        AllowOrigins:
          # - https://github.io
          - https://github.io
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Amz-Date
          - X-Api-Key
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        MaxAge: 600

      Auth:
        DefaultAuthorizer: LambdaTokenAuthorizer
        Authorizers:
          LambdaTokenAuthorizer:
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            AuthorizerPayloadFormatVersion: "1.0"
            Identity:
              Headers:
                - Authorization

  # =========================
  # CONTAINERS
  # =========================

  ContainersListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/containers/containers-list.handler
      Runtime: nodejs24.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AWSHomeDBTable
      Events:
        GetContainers:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyServerlessApi
            Path: /containers
            Method: GET

  ContainerGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/containers/containers-get.handler
      Runtime: nodejs24.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AWSHomeDBTable
      Events:
        GetContainerById:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyServerlessApi
            Path: /containers/{id}
            Method: GET

  ContainerCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/containers/containers-create.handler
      Runtime: nodejs24.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AWSHomeDBTable
      Events:
        PostContainer:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyServerlessApi
            Path: /containers
            Method: POST

  ContainerDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/containers/containers-delete.handler
      Runtime: nodejs24.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AWSHomeDBTable
      Events:
        DeleteContainerById:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyServerlessApi
            Path: /containers/{id}
            Method: DELETE

  ContainerUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/containers/containers-update.handler
      Runtime: nodejs24.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AWSHomeDBTable
      Events:
        UpdateContainerById:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyServerlessApi
            Path: /containers/{id}
            Method: PUT

  # =========================
  # ITEMS
  # =========================

  ItemCreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/items/items-create.handler
      Runtime: nodejs24.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AWSHomeDBTable
      Events:
        PostItem:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyServerlessApi
            Path: /containers/{containerId}/items
            Method: POST

  ItemsListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/items/items-list.handler
      Runtime: nodejs24.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AWSHomeDBTable
      Events:
        GetItems:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyServerlessApi
            Path: /containers/{containerId}/items
            Method: GET

  ItemGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/items/items-get.handler
      Runtime: nodejs24.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AWSHomeDBTable
      Events:
        GetItemById:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyServerlessApi
            Path: /containers/{containerId}/items/{itemId}
            Method: GET

  ItemUpdateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/items/items-update.handler
      Runtime: nodejs24.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AWSHomeDBTable
      Events:
        PutItem:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyServerlessApi
            Path: /containers/{containerId}/items/{itemId}
            Method: PUT

  ItemDeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/items/items-delete.handler
      Runtime: nodejs24.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AWSHomeDBTable
      Events:
        DeleteItem:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyServerlessApi
            Path: /containers/{containerId}/items/{itemId}
            Method: DELETE

  # =========================
  # LOGIN (PUBLIC)
  # =========================

  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/login.handler
      Runtime: nodejs24.x
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AWSHomeDBTable
      Events:
        LoginUser:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyServerlessApi
            Path: /login
            Method: POST
            Auth:
              Authorizer: NONE

  # =========================
  # AUTHORIZER
  # =========================

  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: src/handlers/authorizer.handler
      Runtime: nodejs24.x

  # =========================
  # DYNAMODB
  # =========================

  AWSHomeDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Data"
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: category
          AttributeType: S
        - AttributeName: purchasedFrom
          AttributeType: S
        - AttributeName: itemName
          AttributeType: S
        - AttributeName: warrantyExpiryDate
          AttributeType: S
        - AttributeName: entityType
          AttributeType: S

      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

      GlobalSecondaryIndexes:
        - IndexName: CategoryIndex
          KeySchema:
            - AttributeName: category
              KeyType: HASH
          Projection:
            ProjectionType: ALL

        - IndexName: PurchasedFromIndex
          KeySchema:
            - AttributeName: purchasedFrom
              KeyType: HASH
          Projection:
            ProjectionType: ALL

        - IndexName: ItemNameIndex
          KeySchema:
            - AttributeName: itemName
              KeyType: HASH
          Projection:
            ProjectionType: ALL

        - IndexName: WarrantyIndex
          KeySchema:
            - AttributeName: entityType
              KeyType: HASH
            - AttributeName: warrantyExpiryDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

      SSESpecification:
        SSEEnabled: true

      Tags:
        - Key: Application
          Value: AWSHomeDB

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${MyServerlessApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/"
